### ISSUE TITLE
right mouse button should work by default

### ISSUE THREAD

**Issue by imadsousou** [clearlinux/clr-desktop-defaults#4]

**Comment by mrkz** [comment]
this should be addressed with the release [V16](https://github.com/clearlinux/clr-desktop-defaults/releases/tag/V16), we just merged this on CLR and should be available shortly.

**Comment by jairglez** [comment]
I can confirm the issue is gone on 26730.

**Comment by AthenasJimenez** [comment]
> I can confirm the issue is gone on 26730.

+1
